export enum DemographicsEnum {
  null,
  'Alaska Native',
  'Portuguese',
  'Saponi',
  'Nonbinary',
  'Penobscot',
  'Native Pacific Islander',
  'Japanese',
  'Miami',
  'French',
  'Tunica Biloxi',
  'Greek',
  'Prefer to Self-Identify',
  'Sault',
  'Iraqi',
  'Bolivians',
  'Chickahominy',
  'Modoc',
  'Confederated Tribes of the Colville Reservation',
  'Irish',
  'Armenian',
  'Chickasaw',
  'Chippewa',
  'Russian',
  'Arapaho',
  'Osage',
  'American Indian',
  'Lummi',
  'Gay',
  'South Asian',
  'Poospatuck',
  'Nepali',
  'Chitimacha',
  'Wanapum',
  'Catawba',
  'Afghani',
  'Sri Lankan',
  'Brazilian',
  'Ottawa',
  'Navajo',
  'Transgender',
  'Transgender Male to Female',
  'Nepalese',
  'Asexual',
  'Rappahannock',
  'Hispanic',
  'Lithuanian',
  'Kaw',
  'Cayuse',
  'Haitian',
  'Spanish',
  'Native Hawaiian',
  'LGBTQIA+',
  'Sac and Fox Nation',
  'Crow',
  'Ethiopian',
  'Vietnamese',
  'Filipino',
  'Shawnee',
  'Black or African American',
  'Maliseet',
  'Jamaican',
  'Yavapai',
  'Genderqueer',
  'Cambodian',
  'Wichita',
  'Taiwanese',
  'Onondaga',
  'Mohawk',
  'Wampanoag (Aquinnah)',
  'Latino',
  'Pequot',
  'Czech',
  'Shoshone',
  'Serbian',
  'Caribbean',
  'Gila River Indian Community',
  'Indian',
  'German',
  'Yaqui',
  'Maltese',
  'LGBTQ Ally',
  'Lebanese',
  'Ponca',
  'Transgender Female to Male',
  'Intersex',
  'Seneca Nation of Indians',
  'Passamaquoddy',
  'Swedish',
  'Laguna Pueblo',
  'Tuscarora',
  'Pakistani',
  'Fort Yuma Quechan',
  "Coeur d'Alene Tribe",
  'Italian',
  'Narragansett',
  'Lesbian',
  'White',
  'Iroquois',
  'Hopi',
  'Mexican',
  'Micmacs',
  'Cherokee',
  'Slovak',
  'Creek',
  'Menominee',
  'Bisexual',
  'Asian',
  'Korean',
  'Ukrainian',
  'Seminole',
  'Nez Perce',
  'Choctaws',
  'Jewish',
  'Native Hawaiian or Other Pacific Islander',
  'Iranian',
  'Spokane',
  'Danish',
  'Male',
  'Kootenai',
  'Chinese',
  'Isleta Pueblo',
  'Finnish',
  'Winnebago',
  'Bengal',
  'Comanche',
  'Arabic',
  'Cheyenne',
  'African American',
  'St. Regis',
  'Mohegans',
  'Miccosukee',
  'Alabama-Coushatta',
  'Laotian',
  'Hungarian',
  'African',
  'Spirit Lake Tribe',
  'Norwegian',
  'Sioux',
  'Southeast Asian',
  'American Indian or Alaska Native',
  'Swiss',
  'Walla Walla',
  'Puerto Rican',
  'Cuban',
  'Shinnecock',
  'Caddo',
  'Hoopa',
  "Tohono O'odham",
  'Polish',
  'Slovene',
  'Scottish',
  'Two-Spirit',
  'Pamunkey',
  'Hmong',
  'West Asian',
  'Syrian',
  'Paiute',
  'Mohican',
  'Native Alaskan',
  'Cayuga',
  'Oneida',
  'Apache',
  'Female',
  'Cowlitz',
  'Coushatta',
  'Umatilla',
  'Black',
  'Middle Eastern',
  'Salish',
}
