export enum MiscellaneousCriteriaEnum {
  'Accepted into a Sanctioned International Study Program',
  'Animal Care Experience',
  'Pilot in Training',
  'Demonstrate Leadership, Dependability, and Citizenship',
  'Respect and Value Diversity',
  'LGBTQ Advocate',
  'Participate in Travel Abroad Program',
  'Conscientious Objector',
  'Demonstrate Academic Achievement and Motivation to Succeed in College',
  'Agnostic',
  'Demonstrate Artistic Talent',
  'Bilingual',
  'Theatre Experience at a Local Community Theatre',
  'Demonstrate Leadership, Ambition, Achievement, and Good Academic Standing',
  'Amateur Radio License',
  'Demonstrate Leadership Abilities',
  'Demonstrate Strong Character',
  'Demonstrates the Most Compassion in Caring and Treatment of Patients',
  'Tall Stature',
  'Other',
  'Demonstrate a Strong Christian Faith',
  'Demonstrate Strong Academic Achievement',
  'Demonstrate a Commitment to Improving the Quality of Life of Others',
  'English Is Second Language',
  'Demonstrate Character and Leadership Qualities',
  'All-Academic Team Honors',
  'Pilot',
  'Demonstrate Good Character and Standing in the Community',
  'Possess a Desire to Achieve',
  'Eagle Scout',
  'Participant in a Fire Cadet Program',
  'Demonstrate Good Character',
  'Demonstrate a Strong Work Ethic',
  'Employed at an Asian Restaurant',
  'Atheist',
  'Humanist',
  'Completed Latin Studies In High School',
  'Fluent in Spanish',
  'Demonstrate Optimism and Determination',
  null,
}
