export enum DegreeSeekingEnum {
  'Professional Badge',
  'PhD',
  '1-year Certificate',
  'High School',
  'GED',
  'Professional Micro-credential',
  'Law Degree',
  'Professional Certification',
  'MBA',
  'Doctor of Medicine',
  'Associate Degree',
  'Graduate Degree',
  "Bachelor's Degree",
  'MFA',
}
