export enum FieldsOfStudyEnum {
  null,
  'Wildlife Biology.',
  'Costume',
  'Energy Law',
  'Social Services',
  'Mathematics, General.',
  'Environmental Biology.',
  'Anthropology.',
  'Massage Therapy and Bodywork',
  'Child care Director',
  'Outdoor Education.',
  'Cast Metal Industry',
  'Electrical/Electronics Maintenance and Repair Technology.',
  'Bilingual and Multicultural Education',
  'Occupational Therapist Assistant',
  'General Sales, Merchandising and Related Marketing Operations.',
  'Music History, Literature, and Theory.',
  'Wildlife, Fish and Wildlands Science and Management.',
  'Sports and Fitness Management',
  'Mathematics.',
  'Latin Language',
  'Physical Science Technologies/Technicians.',
  'Apparel and Textile Science',
  'Archives',
  'Slavic Studies',
  'Journalism.',
  'Equine Studies',
  'Biological/Biosystems Engineering.',
  'International Relations',
  'Agricultural and Food Products Processing',
  'Electrical, Electronics and Communications Engineering.',
  'Hospitality Administration/Management.',
  'Tax Law',
  'Agricultural and Horticultural Plant Breeding.',
  'Human Resources Management/Personnel Administration, General.',
  'Truck and Bus Driver/Commercial Vehicle Operator and Instructor.',
  'Electronics Equipment Installation and Repair',
  'Electrocardiograph Technology/Technician.',
  'Parliamentary Procedure',
  'Agronomy and Crop Science.',
  'Fashion/Apparel Design.',
  'Ceramics',
  'Biblical Studies',
  'Dancing.',
  'Historical Preservation',
  'Clinical/Medical Laboratory Assistant.',
  'Social Studies Teacher Education.',
  'Kidney Disease',
  'Banking and Financial Support Services.',
  'Small Business Management',
  'Precision Systems Maintenance and Repair Technologies, Other.',
  'Welding',
  'Theological and Ministerial Studies',
  'Architecture.',
  'Management Sciences and Information Systems',
  'Kinesiotherapy/Kinesiotherapist.',
  'Business/Office Automation/Technology/Data Entry.',
  'Jewish Studies',
  'Materials Science.',
  'General Construction Trades',
  'Land Use Planning and Management/Development.',
  'Agricultural Mechanics and Machinery',
  'Water Quality and Wastewater Treatment Management and Recycling Technology/Technician.',
  'Business Administration and Management, General.',
  'Culinary Arts and Related Services.',
  'Actuarial Science.',
  'Airline/Commercial/Professional Pilot and Flight Crew.',
  'Communication Disorders Sciences and Services.',
  'German History',
  'Interdisciplinary Studies',
  'International Studies',
  'Missionary Studies',
  'Radiologist Assistant.',
  'Theater Education',
  'Packaging',
  'Industrial and Organizational Psychology',
  'Sciences',
  'Sign Language',
  'Health Professions and Related Clinical Sciences, Other.',
  'Computer Systems Analysis',
  'Geological/Geophysical Engineering.',
  'Foodservice Systems Administration/Management.',
  'Engineering/Industrial Management.',
  'Fine/Studio Arts, General.',
  'Speech-Language Pathology/Pathologist.',
  'Accounting.',
  'Film/Cinema/Video Studies.',
  'Medical Records Technician',
  'Religious/Sacred Music.',
  'Biology, General.',
  'Structural Engineering',
  'Engine Machinist.',
  'International Law and Legal Studies.',
  'Paralegal',
  'Welding Engineering',
  'Social Sciences, General.',
  'Metal and Jewelry Arts',
  'Counseling Psychology',
  'Environmental Law',
  'Agricultural Mechanization.',
  'Math',
  'Journalism',
  'Operations Management',
  'Reading.',
  'Pharmacy and Pharmaceutical Sciences',
  'Costume Design.',
  'Law Libraries and Librarianship',
  'Hydraulic Engineering',
  'Liberal Arts and Sciences, General Studies and Humanities.',
  'Occupational Therapist Assistant.',
  'Ceramic Arts and Ceramics.',
  'Child Development',
  'Nonprofit and Public Management',
  'Law and Legal Studies',
  'Environmental Studies.',
  'Equestrian/Equine Studies.',
  'Mathematics, Other.',
  'Environmental Engineering Technician',
  'Employee Benefits',
  'Divinity/Ministry.',
  'Public Health Nursing',
  'Medical Residency Programs - Subspecialty Certificates.',
  'Natural Resources Management and Policy, Other.',
  'Information Technology',
  'French Language and Literature',
  'Japanese Language and Literature',
  'Data Processing',
  'Water Resources Engineering.',
  'Medical Insurance Coding',
  'Liberal Arts and Humanities',
  'Hair Design',
  'Medicine.',
  'HVAC and Refrigeration Engineering Technician',
  'Utilities',
  'Secondary Education and Teaching.',
  'Metal and Jewelry Arts.',
  'International Law',
  'Alternative Medicine and Holistic Health',
  'Business Law',
  'Religion/Religious Studies.',
  'Autobody/Collision and Repair Technology/Technician.',
  'Truck, Bus, and Commercial Vehicle Operation',
  'Advanced/Graduate Dentistry and Oral Sciences.',
  'Forensic Science and Technology',
  'City/Urban, Community and Regional Planning.',
  'Pomology',
  'Alaska Native or American Indian Studies',
  'Atmospheric Sciences and Meteorology',
  'Broadcast Engineering',
  'Archeology.',
  'Music Pedagogy.',
  'Textiles',
  'International/Global Studies.',
  'Real Estate',
  'Law Enforcement Investigation and Interviewing.',
  'Accounting and Related Services.',
  'Funeral Service and Mortuary Science',
  'Family and Consumer Sciences/Human Sciences, General.',
  'Pastoral Counseling and Specialized Ministries.',
  'Biochemistry, Biophysics, and Molecular Biology',
  'Audiology',
  'Environmental Sustainability',
  'Special Education and Teaching.',
  'Palliative Care Nursing',
  'Water Resources',
  'Commercial and Advertising Art.',
  'Accounting and Finance.',
  'Energy Management and Systems Technology/Technician.',
  'Horticultural Science.',
  'Industrial Electronics Technician',
  'Behavioral Aspects of Health.',
  'Logistics and Supply Chain Management',
  'Radio, Television, and Digital Communication.',
  'Surveying Technology/Surveying.',
  'Practical Nursing, Vocational Nursing and Nursing Assistants.',
  'Aquatic Biology/Limnology.',
  'Geology and Earth Science',
  'Pre-Dentistry Studies.',
  'Museum Studies',
  'Advanced/Graduate Dentistry and Oral Sciences, Other.',
  'Bioengineering and Biomedical Engineering',
  'Graphic Communications',
  'Fire Protection.',
  'Economics',
  'Art Therapy',
  'Corrections.',
  'Financial Engineering',
  'Hotel/Motel Administration/Management.',
  'Pre-Occupational Therapy Studies.',
  'Property Management',
  'Lithuanian History',
  'Turfgrass Science',
  'Agricultural Engineering',
  'Business Reporting',
  'Musical Theatre.',
  'Vehicle Maintenance and Repair Technologies, General.',
  'Agricultural Business',
  'Recreation',
  'Polish History',
  'Mining and Petroleum Engineering',
  'Law.',
  'Cultural Studies/Critical Theory and Analysis.',
  'Graphic Arts',
  'Floriculture/Floristry Operations and Management.',
  'Statistics, General.',
  'Construction Engineering',
  'Construction Engineering.',
  'Human Resources Management and Services, Other.',
  'Forestry Engineering',
  'Kinesiology and Exercise Science.',
  'Norwegian History',
  'Exercise Physiology',
  'Dance.',
  'Animal Behavior and Ethology.',
  'Computational and Applied Mathematics',
  'Pest Management',
  'Natural Resources Management and Policy.',
  'Electrical Engineering',
  'Nursing, Other.',
  'Elementary Education',
  'Business Administration, Management and Operations, Other.',
  'Home Health Aide/Home Attendant.',
  'Marine Transportation.',
  'Communications',
  'Early Childhood Education and Teaching.',
  'Higher Education',
  'Music Therapy/Therapist.',
  'Microbiology, General.',
  'Molecular Biology.',
  'Economics.',
  'Library Science and Administration.',
  'Counseling Psychology.',
  'Astronomy and Astrophysics.',
  'Operating Room Nursing',
  'Italian Studies',
  'Medical Laboratory Technician',
  'Creative Writing.',
  'Dairy Husbandry and Production.',
  'Illustration.',
  'Organizational Leadership.',
  'International Agriculture.',
  'Child Development.',
  'Aircraft Pilot (Private).',
  'Mobil Crane Operation/Operator.',
  'Communications Engineering',
  'Nursing/Registered Nurse (RN, ASN, BSN, MSN).',
  'Real Estate Development.',
  'Early Childhood Education',
  'Advertising',
  'Philosophy',
  'Rhetoric and Composition/Writing Studies.',
  'Economics, General.',
  'Natural Sciences.',
  'Publishing.',
  'Behavioral Sciences.',
  'Fire Protection and Prevention',
  'Industrial Production Technologies/Technicians.',
  'Agricultural Teacher Education',
  'Public Administration',
  'Forestry.',
  'Art.',
  'Employment Law',
  'Textile Engineering',
  'Intelligence',
  'Forensic Psychology',
  'Design and Visual Communications',
  'Peace Studies and Conflict Resolution.',
  'Social Studies Teacher Education',
  'Physics, General.',
  'Spanish Language and Literature',
  'Physical Sciences',
  'Marketing',
  'Computer Engineering, General.',
  'Library Science',
  'Master of Divinity',
  'Maritime Studies.',
  'Forestry',
  'Environmental Health.',
  'Nursing Assistant',
  'Animal Sciences, General.',
  'Packaging Engineering',
  'Foreign Languages and Literatures, General.',
  'Data Processing.',
  'Organizational Behavior Studies',
  'Plant Nursery Operations and Management.',
  'Digital Communication and Media/Multimedia.',
  'Norwegian Studies',
  'Electrical/Electronics Equipment Installation and Repair, General.',
  'Health Policy',
  'Food and Nutrition',
  'Child Care Provider/Assistant.',
  'Arts and Crafts',
  'Vocational High School and Secondary Business/Vocational-Industrial/Occupational Diploma Program.',
  'Folklore',
  'Graphic Communications.',
  'Music Technology',
  'Christian Studies.',
  'Youth Ministry.',
  'Religious Education',
  'Metals',
  'Performing Arts',
  'Occupational Therapy/Therapist.',
  'Ground Transportation',
  'Manufacturing',
  'Computer Engineering Technician',
  'Teacher Education, Multiple Levels.',
  'Plant Science',
  'Surveying Technician',
  'Land Management',
  'Playwriting and Screenwriting',
  'Technology Education',
  'American History',
  'Architecture and Related Services, Other.',
  'Homeland Security, Law Enforcement, Firefighting and Related Protective Services, Other.',
  'Chinese Language and Literature',
  'Surgical Technologist',
  'Illustration',
  'Developmental and Child Psychology',
  'Plumbing and Related Water Supply Services.',
  'Petroleum Industry',
  'Rehabilitation Nursing',
  'Playwriting and Screenwriting.',
  'Speech Language Pathology',
  'Criminal Justice/Police Science.',
  'Gifted and Talented Education',
  'Clinical/Medical Social Work.',
  'Adult and Continuing Education',
  'Art History, Criticism and Conservation.',
  'Portuguese Language',
  'Industrial and Product Design',
  'Art Teacher Education.',
  'Mechanical Engineering',
  'Polish Studies',
  'Multi/Interdisciplinary Studies, Other.',
  'Interior Design.',
  'Slavic, Baltic and Albanian Languages, Literatures, and Linguistics.',
  'Art/Art Studies, General.',
  'Italian Language and Literature',
  'Cardiovascular Technician',
  'Teaching',
  'Emergency Care Attendant (EMT Ambulance).',
  'Physics, Other.',
  'Veterinary Medicine.',
  'Physics.',
  'Architectural Engineering',
  'Disability Law',
  'Children and Youth Library Services.',
  'Materials Science',
  'Dance',
  'Naval Engineering',
  'Graphic Design.',
  'Musicology and Ethnomusicology.',
  'Library and Archives Assisting.',
  'Scottish History',
  'Petroleum Engineering',
  'Work and Family Studies.',
  'Golf Industry',
  'auto',
  'Aerospace Engineering',
  'International Business',
  'Advertising.',
  'Disability Studies.',
  'Cyber/Electronic Operations and Warfare.',
  'Investments and Securities.',
  'Drawing',
  'Dramatic/Theatre Arts and Stagecraft, Other.',
  'Manufacturing Technology.',
  'Military Science',
  'British Studies',
  'Fine Arts and Art Studies, Other.',
  'Systems Engineering',
  'Foods, Nutrition, and Wellness Studies',
  'General Office Occupations and Clerical Services.',
  'Naval Architecture and Marine Engineering.',
  'Agroecology and Sustainable Agriculture.',
  'Pharmacology and Toxicology.',
  'High School Education',
  'Business Libraries and Librarianship',
  'Photography.',
  'Art History',
  'Plumbing Technology/Plumber.',
  'Industrial Engineering',
  'Licensed Practical/Vocational Nurse Training (LPN, LVN, Cert.',
  'Spanish Language Teacher Education.',
  'History, General.',
  'Marine Biology and Biological Oceanography.',
  'Real Estate Law',
  'Public Administration.',
  'Registered Nursing/Registered Nurse.',
  'Mechanical Engineering.',
  'Literature.',
  'Sports Management and Leisure Studies',
  'Scottish Language',
  'Pre-Nursing Studies.',
  'Rehabilitation and Therapeutic Professions.',
  'Sign Language Interpretation and Translation.',
  'Health Care Law',
  'Clinical/Medical Laboratory Science/Research and Allied Professions.',
  'Interior Architecture.',
  'Engineering',
  'Dental Clinical Sciences, General.',
  'Pharmacy',
  'Construction Trades, General.',
  'Public Service',
  'Hawaiian Language',
  'Mechanical Drafting and Mechanical Drafting CAD/CADD.',
  'Clinical Laboratory Science/Medical Technology/Technologist.',
  'Construction and Heavy Equipment Operation',
  'Music',
  'Culinary Arts',
  'Japanese Language and Literature.',
  'Vacuum sciences',
  'Adolescents',
  'Military History',
  'Taxation',
  'Engineering Physics',
  'Family Medicine.',
  'Computer Systems Technician',
  'Surveying Engineering',
  'Optical Engineering',
  'Creative Arts',
  'Resource Management',
  'Health and Physical Education/Fitness, General.',
  'Sports Communication.',
  'Veterinary Sciences',
  'Anatomy',
  'Nail Technician',
  'Culinary Arts and Food Service',
  'Industrial Engineering.',
  'Medical Insurance Billing and Claims',
  'Chiropractic.',
  'Dental Hygiene',
  'Public Health Medicine.',
  'Game Design and Interactive Media',
  'Aircraft Powerplant Technology/Technician.',
  'Occupational and Environmental Health Nursing.',
  'Photography',
  'Precision Production Trades, General.',
  'Architectural Engineering Technologies/Technicians.',
  'Agronomy',
  'Machine Tool Technology/Machinist.',
  'Plant Sciences.',
  'Tourism',
  'Social Welfare',
  'Communication Disorders',
  'Occupational Therapy',
  'Corrections and Criminal Justice, Other.',
  'Radiologic Technology/Science - Radiographer.',
  'Public Policy and Social Services',
  'Wine Steward/Sommelier.',
  'Composers and Compositions',
  'Animal Law',
  'Agricultural and Domestic Animal Services.',
  'Mental Health Counseling',
  'Business',
  'Editors and Editing',
  'Physical Education Teaching and Coaching.',
  'Drafting and Design Technology/Technician, General.',
  'Political Science and Government',
  'Industrial Technology/Technician.',
  'Public Relations',
  'Network, Database, and System Administration',
  'Management',
  'Acting',
  'Computer Software Engineering.',
  'English and Writing',
  'Plant Sciences, General.',
  'Arts Management.',
  'Graphic Design',
  'Design',
  'Health Teacher Education',
  'Boating Industry',
  'Computer Science',
  'Speech Impairments',
  "Alzheimer's Disease",
  'Financial Planning and Services.',
  'Electrician.',
  'Computer Systems Networking and Telecommunications.',
  'Evolution',
  'Animal Sciences and Husbandry',
  'Robotics and Automation Engineering Technician',
  'Community Development',
  'Stringed Instruments.',
  'Arts, Entertainment,and Media Management, General.',
  'Insurance.',
  'Computer Installation and Repair',
  'Business Administration, Management and Operations.',
  'Architectural Drafting and Architectural CAD/CADD.',
  'Fashion and Apparel Merchandising',
  'Engineering Science',
  'Environmental Education',
  'Business/Commerce, General.',
  'Apparel and Textiles, General.',
  'Strategic Intelligence.',
  'Critical Care Nursing',
  'Fashion and Fabric Consultant.',
  'Ceramic Engineering',
  'Botany and Plant Physiology',
  'Speech Communication and Rhetoric.',
  'Aeronautics and Aviation Technology',
  'Technical and Business Writing.',
  'Family and Consumer Studies',
  'Aged and Aging',
  'Esthetician and Skin Care',
  'Film and Video Studies',
  'Phlebotomy Technician/Phlebotomist.',
  'Electrical, Electronics and Communications Engineering, Other.',
  'Sports Reporting',
  'Geriatrics Nursing',
  'Entertainment Law',
  'CAD/CADD Drafting and/or Design Technology/Technician.',
  'Pediatric Hemato-Oncology.',
  'Radiology Nursing',
  'Philanthropy',
  'Architecture',
  'International Relations and Affairs.',
  'Alutiiq culture',
  'Organ Transplants',
  'Surgical Technology/Technologist.',
  'Business and Management',
  'Chemistry, General.',
  'Soil Sciences.',
  'Health and Wellness, General.',
  'Music Teacher Education',
  'Medical Assistant',
  'Pharmacy, Pharmaceutical Sciences, and Administration.',
  'Native American Studies',
  'Bioinformatics',
  'Substance Abuse and Addiction Counseling',
  'Music Management',
  'Dietetics and Clinical Nutrition Services, Other.',
  'Dentistry.',
  'Neuroscience.',
  'Physical Therapy',
  'Physical Therapy/Therapist.',
  'Minority and Ethnic Studies',
  'Corporate Law',
  'Internal Medicine.',
  'Mental and Social Health Services',
  'Nuclear Engineering',
  'Medical Social Work',
  'Computer Technology/Computer Systems Technology.',
  'Apparel and Textiles.',
  'Heating, Air Conditioning, Ventilation & Refrigeration Maintenance Tech (HAC, HACR, HVAC, HVACR)',
  'Textile Technology',
  'Natural Resources',
  'Anesthesiology Nursing',
  'Ecology',
  'Radiologic Technician',
  'Classical, Ancient Mediterranean and Near Eastern Studies and Archaeology.',
  'Allied Health and Medical Assisting Services.',
  'Commercial and Advertising Art',
  'Water resources',
  'Cellular Biology',
  'Manufacturing Engineering.',
  'Heating, Air Conditioning, Ventilation and Refrigeration Maintenance Technology/Technician.',
}
